baseURL: "https://samsonyuenhk.github.io/" 
title: Samson Yuen
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Resume
          url: cv_rosa2.pdf
          weight: 3 
        # - name: Photography
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am an Associate Professor of Political Science."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Samson Yuen
          subtitle: "I am a political scientist who is interested in contentious politics, conflict processes, public opinion and state-society relations, with a regional focus on China and East Asia. Currently, I am Associate Professor of Political Science at the Department of Government and International Studies of Hong Kong Baptist University. I am also the Director of the Comparative Governance and Policy Research Centre, Hong Kong Baptist University. I have been a visiting fellow in the Australia Centre on China in the World, Australian National University. My research has been published in Democratization, Geopolitics, Government and Opposition, Journal of Conflict Resolution, Journal of Peace Research, Journal of Contemporary China, Mobilization, Political Psychology, Political Studies, Social Movement Studies, The China Quarterly, and others. My book, The Making of Leaderful Mobilization: Power and Contention in Hong Kong (coauthored book with Edmund W. Cheng), is published by Cambridge University Press under the Cambridge Series in Contentious Politics. I serve on the executive committee of the Hong Kong Political Science Association and the editorial board of China Perspectives. "
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Samson Yuen
          buttons:
            - name: Publications
              url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
           # - name: Newsletter
           #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            - name: Talks
              url: talks/
            - name: Resume
              url: cv_rosa2.pdf
            #- name: Archive
            #  url: archive/
    socialIcons:
        # - name: CV
        #   url: cv_rosa.pdf
        - name: Email
          url: mailto:rosa.van-den-ende@univ-paris1.fr
        - name: Location
          url: location/
    
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=jwrYE5sAAAAJ&hl=fr
        - name: LinkedIn
          url: https://linkedin.com/in/rosavandenende
        # - name: GitHub
        #   url: https://github.com/pmichaillat
        - name: ORCID
          url: https://orcid.org/0000-0002-9417-1075
      

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rosa van den Ende"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
